# .github/workflows/web.yml
name: Deploy website
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create pages
      run: make

    - name: Deploy
      uses: actions/deploy-pages@v4
      publish_dir: ./_site  # <-- Deploy the '_site' folder

