# .github/workflows/web.yml
name: Deploy website
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      name: Deploy
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/master'
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./_site  # <-- Deploy the '_site' folder

